create_clock -period 20.000 -name sys_clk [get_ports sys_clk]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets sys_clk]
create_clock -period 20.000 -name cmos_pclk [get_ports cam_pclk]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets cam_pclk_IBUF]


set_property PACKAGE_PIN M25 [get_ports cam_pclk]
set_property IOSTANDARD LVCMOS33 [get_ports cam_pclk]
set_property PACKAGE_PIN N26 [get_ports {cam_data[0]}]
set_property PACKAGE_PIN R26 [get_ports {cam_data[1]}]
set_property PACKAGE_PIN M26 [get_ports {cam_data[2]}]
set_property PACKAGE_PIN P26 [get_ports {cam_data[3]}]
set_property PACKAGE_PIN N19 [get_ports {cam_data[4]}]
set_property PACKAGE_PIN M21 [get_ports {cam_data[5]}]
set_property PACKAGE_PIN M20 [get_ports {cam_data[6]}]
set_property PACKAGE_PIN M22 [get_ports {cam_data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cam_data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cam_data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cam_data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cam_data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cam_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cam_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cam_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cam_data[0]}]
set_property PACKAGE_PIN AB21 [get_ports tmds_clk_p]
set_property PACKAGE_PIN AE22 [get_ports tmds_oen]
set_property PACKAGE_PIN AF24 [get_ports {tmds_data_p[0]}]
set_property PACKAGE_PIN AE23 [get_ports {tmds_data_p[1]}]
set_property PACKAGE_PIN AC23 [get_ports {tmds_data_p[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports tmds_oen]
set_property IOSTANDARD LVCMOS33 [get_ports sys_rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports cam_href]
set_property IOSTANDARD LVCMOS33 [get_ports cam_rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports cam_pwdn]
set_property IOSTANDARD LVCMOS33 [get_ports cam_scl]
set_property IOSTANDARD LVCMOS33 [get_ports cam_sda]
set_property IOSTANDARD LVCMOS33 [get_ports cam_vsync]
set_property IOSTANDARD LVCMOS33 [get_ports sys_clk]
set_property PACKAGE_PIN G22 [get_ports sys_clk]
set_property PACKAGE_PIN D26 [get_ports sys_rst_n]
set_property PACKAGE_PIN P21 [get_ports cam_vsync]
set_property PACKAGE_PIN R25 [get_ports cam_href]
set_property PACKAGE_PIN L25 [get_ports cam_pwdn]
set_property PACKAGE_PIN P25 [get_ports cam_rst_n]
set_property PACKAGE_PIN P19 [get_ports cam_scl]
set_property PACKAGE_PIN P20 [get_ports cam_sda]

set_property IOSTANDARD LVCMOS33 [get_ports {result_r[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {result_r[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {result_r[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {result_r[0]}]
set_property PACKAGE_PIN A23 [get_ports {result_r[0]}]
set_property PACKAGE_PIN D23 [get_ports {result_r[1]}]
set_property PACKAGE_PIN C26 [get_ports {result_r[2]}]
set_property PACKAGE_PIN D25 [get_ports {result_r[3]}]
